// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPath() {
  return window['go']['main']['ControlCenterApp']['ConfigPath']();
}

export function GetSettings() {
  return window['go']['main']['ControlCenterApp']['GetSettings']();
}

export function OpenConfigFile() {
  return window['go']['main']['ControlCenterApp']['OpenConfigFile']();
}

export function ResetSettings() {
  return window['go']['main']['ControlCenterApp']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['ControlCenterApp']['SaveSettings'](arg1);
}
