// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function ConfigPath():Promise<string>;

export function GetSettings():Promise<core.Settings>;

export function OpenConfigFile():Promise<void>;

export function ResetSettings():Promise<core.Settings>;

export function SaveSettings(arg1:core.Settings):Promise<core.Settings>;
